name: Publish Vendor Performance Analysis

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert jupyter ipykernel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute & Convert Notebook to HTML
        run: |
          mkdir -p build
          jupyter nbconvert \
            --to html \
            --execute \
            --output index.html --output-dir build \
            ./vendor_performance_analysis.ipynb
          fi

      - name: Execute & Convert Notebook to HTML
        run: |
          mkdir -p build
          jupyter nbconvert \
            --to html \
            --execute \
            --output build/index.html \
            "$NOTEBOOK_FILE"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
